### ISSUE TITLE
Suggestion: Try to stay consistent with code formatting in every part of the code. 

### ISSUE THREAD

**Issue by josephtkim** [mhcd1984/prj-rev-bwfs-tea-cozy#5]
One small but important suggestion is to try to always stay consistent with your code formatting throughout all the code in both HTML and CSS. In the CSS, there were several inconsistencies with the formatting, such as for these lines
https://github.com/mhcd1984/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/CSS/style.css#L96-L131

The formatting for these lines should be changed to stay consistent, like so

```css
.location{
  height: 600px;
  width: 1200px;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-locations-background.jpg");
  background-position: top;
}

.location h2{
  text-align: center;
  padding-top: 30px;
  margin-bottom: 15px;
}

.squares{
  display: flex;
  justify-content: center;
}

.square{
  width: 300px;
  margin-right: 40px;
  background-color: black;
  opacity: 1;
  text-align: center;
}

#corner-right{
  margin-right: 0;
}

.contact{
  text-align: center;
  height: 200px;
}

.copyright{
  padding-left: 20px;
}
```
